# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ###
  #based on patrick's https://github.mandiant.com/pedgett/candyvan/blob/develop/vagrant/Vagrantfile
  #clones a forked MPLEX puppet repo into /tmp for use with staging UAC as it would be in production
  ###

  VAGRANTFILE_DIRECTORY = File.dirname(__FILE__)
  SRC_LOCAL_PATH = Pathname(VAGRANTFILE_DIRECTORY).parent()

  PUPPET_REPO_URL = 'git@github.mandiant.com:atayman/puppet.git'

  # Set this to where we'll pull down our puppet repo
  PUPPET_REPO_DIR = '/tmp/puppet'
  PUPPET_HIERA_DIR = "#{PUPPET_REPO_DIR}/hieradata"

  if ENV['PUPPET_MODULE_DIR']
   puts "Using puppet modules found here #{ENV['PUPPET_REPO_DIR']}"
   PUPPET_MODULE_DIR = ENV['PUPPET_MODULE_DIR']
  else
   puts "Using DEFAULT puppet module dir"
   if Dir.exists?(PUPPET_REPO_DIR)
  	Dir.chdir(PUPPET_REPO_DIR) do
  		PUPPET_MODULE_DIR = "#{PUPPET_REPO_DIR}/modules"
  		system("git pull")
  	end
   else
  	system("git clone #{PUPPET_REPO_URL} #{PUPPET_REPO_DIR}")
  	PUPPET_MODULE_DIR = "#{PUPPET_REPO_DIR}/modules"
   end
  end


  ###
  #if using a virtualbox provider the below will give the vm access to all CPUs and 1/4 total system RAM
  #for better performance
  ###
  config.vm.provider "virtualbox" do |v|
    host = RbConfig::CONFIG['host_os']

    # Give VM 1/4 system memory & access to all cpu cores on the host
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
    elsif host =~ /linux/
      cpus = `nproc`.to_i
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
    else # sorry Windows folks, I can't help you
      cpus = 2
      mem = 1024
    end

    v.customize ["modifyvm", :id, "--memory", mem]
    v.customize ["modifyvm", :id, "--cpus", cpus]
  end

  config.vm.host_name = "uac.vm.mandiant.com"
  config.vm.network "private_network", ip: "10.1.1.128"
  config.vm.box = "centos-65-x64-virtualbox-puppet.box"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box"

  # config.vm.synced_folder SRC_LOCAL_PATH, '/opt/web/apps/uac', :nfs => true
  config.vm.synced_folder PUPPET_HIERA_DIR, '/etc/puppet/hieradata'



  ###
  #trick from https://github.com/mitchellh/vagrant/issues/1807
  #solves really slow NPM installs
  ###
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.vm.provision :puppet do |puppet|
     puppet.options = "--verbose --debug --environment localdev"
     puppet.module_path = PUPPET_MODULE_DIR
     puppet.manifests_path = "./"
     puppet.manifest_file  = "vagrant.pp"
     puppet.hiera_config_path = '/tmp/puppet/hiera.yaml'
   end

end
