-- UAC Database Creation Script

DROP DATABASE IF EXISTS uac;
DROP USER IF EXISTS uac_user;

CREATE USER uac_user WITH PASSWORD 'devnet';

CREATE DATABASE uac OWNER uac_user;
GRANT ALL PRIVILEGES ON DATABASE uac TO uac_user;

-- Allow the generation of UUIDs.
--CREATE EXTENSION "uuid-ossp";

-- Dump a UUID generated by Postgres.
--SELECT
--  uuid_generate_v4();